# Action Detection

In [1]:
import torch
import torch.nn as nn
from torch.autograd import Variable
import torchvision
import numpy as np
from scipy.io import loadmat
from random import shuffle
from torch.utils.data import Dataset, DataLoader
import cv2
import os
from sklearn.model_selection import train_test_split
import re

## Data Loader

In [99]:
video_rootdir="./ReCompress_Videos"
mask_rootdir="./puppet_mask"
pose_rootdir="./joint_positions"

video_pathes=[]
mask_pathes=[]
pose_pathes=[]
for root, dirs, files in os.walk(video_rootdir):
    for file in files:
        if file[0].startswith(".") or root.endswith('.AppleDouble'):
            continue
        video_pathes.append(os.path.join(root, file))

for root, dirs, files in os.walk(mask_rootdir):
    for file in files:
        if file[0].startswith(".") or root.endswith('.AppleDouble'):
            continue
        mask_pathes.append(os.path.join(root, file)) 

for root, dirs, files in os.walk(pose_rootdir):
    for file in files:
        if file[0].startswith(".") or root.endswith('.AppleDouble'):
            continue
        pose_pathes.append(os.path.join(root, file))         

video_pathes = sorted(video_pathes)
mask_pathes = sorted(mask_pathes)
pose_pathes = sorted(pose_pathes)

video_list = [re.findall(r"[\w_]+\d+", x)[0] for x in video_pathes]
mask_list = [re.findall(r"[\w_]+\d+", x)[0] for x in mask_pathes]
pose_list = [re.findall(r"[\w_]+\d+", x)[0] for x in pose_pathes]

# make sure every thing matches
for x, y, z in zip(video_list, mask_list, pose_list):
    assert (x == y) and (x == z)
    


In [19]:
import re

In [105]:
video_pathes = sorted(video_pathes)
mask_pathes = sorted(mask_pathes)
pose_pathes = sorted(pose_pathes)

In [106]:
video_list = [re.findall(r"[\w_]+\d+", x)[0] for x in video_pathes]
print(video_list)

['April_09_brush_hair_u_nm_np1_ba_goo_0', 'April_09_brush_hair_u_nm_np1_ba_goo_1', 'April_09_brush_hair_u_nm_np1_ba_goo_2', 'Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_ba_med_3', 'Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_goo_1', 'Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_goo_2', 'Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_med_0', 'Brushing_Hair_with_Beth_brush_hair_h_nm_np1_le_goo_0', 'Brushing_Hair_with_Beth_brush_hair_u_nm_np1_fr_goo_1', 'Brushing_Hair_with_Beth_brush_hair_u_nm_np1_fr_goo_2', 'Brushing_hair__the_right_way_brush_hair_u_nm_np1_fr_goo_0', 'Brushing_hair__the_right_way_brush_hair_u_nm_np1_fr_goo_1', 'Brushing_hair__the_right_way_brush_hair_u_nm_np1_fr_goo_2', 'Brushing_my_Long_Hair__February_2009_brush_hair_u_nm_np1_ba_goo_1', 'Brushing_my_Long_Hair__February_2009_brush_hair_u_nm_np1_ba_goo_2', '_December_2008_brush_hair_u_cm_np1_ba_goo_1', '_December_2008_brush_hair_u_cm_np1_ba_goo_2', '_December_2008_brush_hai

In [107]:
mask_list = [re.findall(r"[\w_]+\d+", x)[0] for x in mask_pathes]
print(mask_list)

['April_09_brush_hair_u_nm_np1_ba_goo_0', 'April_09_brush_hair_u_nm_np1_ba_goo_1', 'April_09_brush_hair_u_nm_np1_ba_goo_2', 'Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_ba_med_3', 'Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_goo_1', 'Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_goo_2', 'Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_med_0', 'Brushing_Hair_with_Beth_brush_hair_h_nm_np1_le_goo_0', 'Brushing_Hair_with_Beth_brush_hair_u_nm_np1_fr_goo_1', 'Brushing_Hair_with_Beth_brush_hair_u_nm_np1_fr_goo_2', 'Brushing_hair__the_right_way_brush_hair_u_nm_np1_fr_goo_0', 'Brushing_hair__the_right_way_brush_hair_u_nm_np1_fr_goo_1', 'Brushing_hair__the_right_way_brush_hair_u_nm_np1_fr_goo_2', 'Brushing_my_Long_Hair__February_2009_brush_hair_u_nm_np1_ba_goo_1', 'Brushing_my_Long_Hair__February_2009_brush_hair_u_nm_np1_ba_goo_2', '_December_2008_brush_hair_u_cm_np1_ba_goo_1', '_December_2008_brush_hair_u_cm_np1_ba_goo_2', '_December_2008_brush_hai

In [108]:
pose_list = [re.findall(r"[\w_]+\d+", x)[0] for x in pose_pathes]
print(pose_list)

['April_09_brush_hair_u_nm_np1_ba_goo_0', 'April_09_brush_hair_u_nm_np1_ba_goo_1', 'April_09_brush_hair_u_nm_np1_ba_goo_2', 'Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_ba_med_3', 'Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_goo_1', 'Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_goo_2', 'Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_med_0', 'Brushing_Hair_with_Beth_brush_hair_h_nm_np1_le_goo_0', 'Brushing_Hair_with_Beth_brush_hair_u_nm_np1_fr_goo_1', 'Brushing_Hair_with_Beth_brush_hair_u_nm_np1_fr_goo_2', 'Brushing_hair__the_right_way_brush_hair_u_nm_np1_fr_goo_0', 'Brushing_hair__the_right_way_brush_hair_u_nm_np1_fr_goo_1', 'Brushing_hair__the_right_way_brush_hair_u_nm_np1_fr_goo_2', 'Brushing_my_Long_Hair__February_2009_brush_hair_u_nm_np1_ba_goo_1', 'Brushing_my_Long_Hair__February_2009_brush_hair_u_nm_np1_ba_goo_2', '_December_2008_brush_hair_u_cm_np1_ba_goo_1', '_December_2008_brush_hair_u_cm_np1_ba_goo_2', '_December_2008_brush_hai

In [110]:
# make sure every thing matches
for x, y, z in zip(video_list, mask_list, pose_list):
    assert (x == y) and (x == z)

In [84]:
print(len(video_pathes))

928


In [83]:
print(video_pathes)

['./ReCompress_Videos/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_0.avi', './ReCompress_Videos/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_1.avi', './ReCompress_Videos/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_2.avi', './ReCompress_Videos/brush_hair/Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_ba_med_3.avi', './ReCompress_Videos/brush_hair/Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_goo_1.avi', './ReCompress_Videos/brush_hair/Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_goo_2.avi', './ReCompress_Videos/brush_hair/Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_med_0.avi', './ReCompress_Videos/brush_hair/brush_my_hair_without_wearing_the_glasses_brush_hair_u_nm_np1_fr_goo_0.avi', './ReCompress_Videos/brush_hair/brush_my_hair_without_wearing_the_glasses_brush_hair_u_nm_np1_fr_goo_2.avi', './ReCompress_Videos/brush_hair/Brushing_hair__the_right_way_brush_hair_u_nm_np1_fr_goo_0.avi', './ReCompress_Videos/brush_hair/Brushing_hair__th

In [5]:
print(mask_pathes)

['./puppet_mask/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_0/puppet_mask.mat', './puppet_mask/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_1/puppet_mask.mat', './puppet_mask/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_2/puppet_mask.mat', './puppet_mask/brush_hair/Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_ba_med_3/puppet_mask.mat', './puppet_mask/brush_hair/Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_goo_1/puppet_mask.mat', './puppet_mask/brush_hair/Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_goo_2/puppet_mask.mat', './puppet_mask/brush_hair/Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_med_0/puppet_mask.mat', './puppet_mask/brush_hair/brush_my_hair_without_wearing_the_glasses_brush_hair_u_nm_np1_fr_goo_0/puppet_mask.mat', './puppet_mask/brush_hair/brush_my_hair_without_wearing_the_glasses_brush_hair_u_nm_np1_fr_goo_2/puppet_mask.mat', './puppet_mask/brush_hair/Brushing_hair__the_right_way_brush_hair_u_nm_np1_fr_goo_0/puppet_

In [6]:
print(pose_pathes)

['./joint_positions/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_0/joint_positions.mat', './joint_positions/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_1/joint_positions.mat', './joint_positions/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_2/joint_positions.mat', './joint_positions/brush_hair/Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_ba_med_3/joint_positions.mat', './joint_positions/brush_hair/Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_goo_1/joint_positions.mat', './joint_positions/brush_hair/Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_goo_2/joint_positions.mat', './joint_positions/brush_hair/Aussie_Brunette_Brushing_Long_Hair_brush_hair_u_nm_np1_fr_med_0/joint_positions.mat', './joint_positions/brush_hair/brush_my_hair_without_wearing_the_glasses_brush_hair_u_nm_np1_fr_goo_0/joint_positions.mat', './joint_positions/brush_hair/brush_my_hair_without_wearing_the_glasses_brush_hair_u_nm_np1_fr_goo_2/joint_positions.mat', './joint_positions/

In [32]:
from sklearn.model_selection import train_test_split

In [85]:
video_pathes_train, video_pathes_valid, mask_pathes_train, mask_pathes_valid, pose_pathes_train, pose_pathes_valid = \
    train_test_split(video_pathes, mask_pathes, pose_pathes, test_size=0.1)
class_names=[name for name in os.listdir(video_rootdir) if not name.startswith(".")]


In [91]:
class JHMDB(torch.utils.data.Dataset):
    def __init__(self, video_pathes, mask_pathes, pose_pathes, class_names):
        
        self.data = {'video': [], 'label': [], 'mask':[], 'pose':[], 'scale':[]}
        
        self.classdict = {}
        for i, x in enumerate(class_names):
            self.classdict[x] = i

        video_num=len(video_pathes)
        mask_num=len(mask_pathes)

        for i in range(video_num):
            video=[]
            cap = cv2.VideoCapture(video_pathes[i])
            has_frame=True
            while(has_frame):
                _, frame = cap.read()
                has_frame = frame is not None

                if has_frame:
                    frame = cv2.resize(frame, (112, 112), interpolation = cv2.INTER_CUBIC) # (112, 112, 3)
                    #frame = np.transpose(frame, (2, 0, 1)) # (3, 112, 112)
                    video.append(frame)
            cap.release()
            self.data['video'].append(video)

            mask_mat = loadmat(mask_pathes[i]) 
            masks = cv2.resize(mask_mat['part_mask'], (112, 112), interpolation = cv2.INTER_CUBIC) # (112, 112, F)
            self.data['mask'].append(masks)
            self.data['label'].append(video_pathes[i].split('/')[-2])
            pose_mat = loadmat(pose_pathes[i])['pos_img']
            scale = loadmat(pose_pathes[i])['scale']
            self.data['pose'].append(pose_mat)
            self.data['scale'].append(scale[0]) # redundant dim
            
            
    def _compute_mean(self):
        meanstd_file = './data/jhmdbmean'
        if os.path.isfile(meanstd_file):
            meanstd = torch.load(meanstd_file)
        else:
            #mean = torch.zeros(3)
            #std = torch.zeros(3)
            mean = np.zeros(3)
            std = np.zeros(3)
            cnt = 0
            for videos in self.data['video']:
                for img in videos:
                    # CxHxW
                    mean += np.reshape(img, (-1, img.shape[-1])).mean(0)
                    std += np.reshape(img, (-1, img.shape[-1])).std(0) 
                    cnt += 1
            mean /= cnt
            std /= cnt
            mean = torch.FloatTensor(mean)
            std = torch.FloatTensor(std)
            meanstd = {
                'mean': mean,
                'std': std,
                }
            torch.save(meanstd, meanstd_file)
            
        print('    Mean: %.4f, %.4f, %.4f' % (meanstd['mean'][0], meanstd['mean'][1], meanstd['mean'][2]))
        print('    Std:  %.4f, %.4f, %.4f' % (meanstd['std'][0], meanstd['std'][1], meanstd['std'][2]))
            
        return meanstd['mean'], meanstd['std']
    
    def __getitem__(self, index):
        # video (F, C, 112, 112) to be reshaped on the fly
        # label scala, 
        # mask (112, 112, F)
        # pose (2, 15, F)
        # scale (F)
        
        frame_num = self.data['mask'][index].shape[2]
        F = 15
        # randomly select 15 consecutive frames (F = 15)
        #start_frame = np.random.randint(0, high=frame_num-F+1)
        
        # randomly select 15 frames
        frame_shuffle=list(range(frame_num))
        shuffle(frame_shuffle)
        selected_frame=sorted(frame_shuffle[0:F])
        pose_data = torch.from_numpy(self.data['pose'][index][:,:,selected_frame].astype('float'))
        
        # change pose position according to resize
        pose_data = torch.from_numpy(self.data['pose'][index][:,:,start_frame:start_frame+F].astype('float'))
        pose_data[0,:,:] = pose_data[0,:,:] * 112 / 240
        pose_data[1,:,:] = pose_data[1,:,:] * 112 / 320
        
        return torch.from_numpy(np.array(self.data['video'][index][start_frame:start_frame+F])).int(), \
            torch.LongTensor([self.classdict[self.data['label'][index]]]), \
            torch.from_numpy(self.data['mask'][index][:,:,start_frame:start_frame+F].astype('float')), \
            pose_data, \
            torch.from_numpy(self.data['scale'][index][start_frame:start_frame+F].astype('float'))
        
    def __len__(self):
        return len(self.data['scale'])

In [435]:
valid_dataset.data['video']

[[array([[[  5,  14,   8],
          [ 10,  22,  18],
          [  9,  24,  20],
          ...,
          [  9,  20,  15],
          [  7,  17,  14],
          [  9,  20,  14]],
  
         [[  8,  17,  11],
          [ 30,  42,  38],
          [ 14,  29,  24],
          ...,
          [ 13,  24,  18],
          [ 11,  20,  18],
          [ 11,  22,  16]],
  
         [[ 10,  21,  15],
          [ 39,  51,  47],
          [ 14,  31,  27],
          ...,
          [ 25,  36,  30],
          [ 15,  26,  20],
          [ 14,  25,  19]],
  
         ...,
  
         [[ 63,  78,  60],
          [ 99, 119, 100],
          [ 92, 112,  93],
          ...,
          [ 20,  39,  30],
          [ 26,  42,  33],
          [ 30,  44,  36]],
  
         [[ 45,  56,  42],
          [108, 123, 109],
          [ 89, 109,  90],
          ...,
          [ 18,  31,  24],
          [ 17,  30,  22],
          [ 12,  23,  18]],
  
         [[ 22,  28,  17],
          [ 59,  72,  59],
          [ 48,  60,  46

In [434]:
len(valid_dataset.data['video'])

10

In [24]:
train_dataset = JHMDB(video_pathes_train, mask_pathes_train, pose_pathes_train, class_names)


In [92]:
valid_dataset = JHMDB(video_pathes_valid, mask_pathes_valid, pose_pathes_valid, class_names)


93


In [93]:
valid_dataset._compute_mean()

(112, 112, 3)
(12544, 3)
[[229 223 213]
 [203 197 187]
 [218 212 202]
 ...
 [ 96  97  92]
 [ 97  98  93]
 [ 98  99  94]]
(112, 112, 3)
(12544, 3)
[[229 223 213]
 [203 197 187]
 [218 212 202]
 ...
 [ 96  97  92]
 [ 97  98  93]
 [ 98  99  94]]
(112, 112, 3)
(12544, 3)
[[229 223 213]
 [203 197 187]
 [218 212 202]
 ...
 [ 96  97  92]
 [ 97  98  93]
 [ 98  99  94]]
(112, 112, 3)
(12544, 3)
[[229 223 213]
 [203 197 187]
 [218 212 202]
 ...
 [ 96  97  92]
 [ 97  98  93]
 [ 98  99  94]]
(112, 112, 3)
(12544, 3)
[[229 223 213]
 [203 197 187]
 [218 212 202]
 ...
 [ 96  97  92]
 [ 97  98  93]
 [ 98  99  94]]
(112, 112, 3)
(12544, 3)
[[229 223 213]
 [203 197 187]
 [218 212 202]
 ...
 [ 96  97  92]
 [ 97  98  93]
 [ 98  99  94]]
(112, 112, 3)
(12544, 3)
[[229 223 213]
 [203 197 187]
 [218 212 202]
 ...
 [ 96  97  92]
 [ 97  98  93]
 [ 98  99  94]]
(112, 112, 3)
(12544, 3)
[[229 223 213]
 [203 197 187]
 [218 212 202]
 ...
 [ 96  97  92]
 [ 97  98  93]
 [ 98  99  94]]
(112, 112, 3)
(12544, 3)
[[229 2

(112, 112, 3)
(12544, 3)
[[ 0  5  4]
 [ 7 15 14]
 [14 24 23]
 ...
 [28 42 29]
 [ 5 18  7]
 [15 27 12]]
(112, 112, 3)
(12544, 3)
[[ 0  8  7]
 [12 22 21]
 [11 21 20]
 ...
 [39 53 39]
 [ 2 14  3]
 [ 8 19  8]]
(112, 112, 3)
(12544, 3)
[[ 1 11 10]
 [ 0  8  7]
 [14 24 23]
 ...
 [40 53 42]
 [39 51 43]
 [30 40 32]]
(112, 112, 3)
(12544, 3)
[[18 28 27]
 [13 23 22]
 [14 24 23]
 ...
 [36 49 38]
 [26 38 30]
 [30 41 35]]
(112, 112, 3)
(12544, 3)
[[18 28 27]
 [13 23 22]
 [15 25 24]
 ...
 [36 49 38]
 [26 38 30]
 [30 41 35]]
(112, 112, 3)
(12544, 3)
[[13 23 22]
 [13 23 22]
 [ 8 18 17]
 ...
 [14 26 18]
 [42 55 44]
 [ 0  8  0]]
(112, 112, 3)
(12544, 3)
[[11 21 20]
 [10 20 19]
 [ 9 19 18]
 ...
 [ 8 20 12]
 [28 41 32]
 [18 31 20]]
(112, 112, 3)
(12544, 3)
[[ 1 11 10]
 [ 2 12 11]
 [ 4 14 13]
 ...
 [ 8 17 15]
 [10 22 14]
 [18 30 22]]
(112, 112, 3)
(12544, 3)
[[149 122  99]
 [149 122  99]
 [149 122  99]
 ...
 [ 79  93  73]
 [ 82  93  74]
 [ 83  93  74]]
(112, 112, 3)
(12544, 3)
[[151 121  99]
 [151 121  99]


(112, 112, 3)
(12544, 3)
[[22 21 19]
 [14 17 15]
 [20 23 21]
 ...
 [11 14 12]
 [ 6 12 11]
 [12 12 10]]
(112, 112, 3)
(12544, 3)
[[21 20 20]
 [18 17 16]
 [23 21 17]
 ...
 [10 12 11]
 [ 8 11 10]
 [ 9 12 10]]
(112, 112, 3)
(12544, 3)
[[17 19 21]
 [14 18 16]
 [18 22 17]
 ...
 [ 5 13 10]
 [ 4 11 10]
 [ 8 11 11]]
(112, 112, 3)
(12544, 3)
[[21 19 21]
 [14 18 16]
 [16 22 17]
 ...
 [ 5 13 10]
 [ 4 10 11]
 [ 8 11  9]]
(112, 112, 3)
(12544, 3)
[[20 16 19]
 [ 6 16 13]
 [18 19 13]
 ...
 [ 2 10  9]
 [ 3  9 10]
 [ 9 13  8]]
(112, 112, 3)
(12544, 3)
[[20 16 19]
 [ 6 16 13]
 [18 19 13]
 ...
 [ 2 10  9]
 [ 3  9 10]
 [ 9 13  8]]
(112, 112, 3)
(12544, 3)
[[19 17 19]
 [ 5 17 12]
 [18 21 17]
 ...
 [ 0  9  6]
 [ 1  9  8]
 [11 12  7]]
(112, 112, 3)
(12544, 3)
[[20 19 19]
 [ 4 16 11]
 [18 20 19]
 ...
 [ 0  9  6]
 [ 1  9  8]
 [11 12  7]]
(112, 112, 3)
(12544, 3)
[[17 17 15]
 [ 4 17 10]
 [20 23 19]
 ...
 [ 3 13 10]
 [ 5 12 11]
 [13 14  8]]
(112, 112, 3)
(12544, 3)
[[17 17 15]
 [ 4 17 10]
 [20 23 19]
 ...
 [ 3 13

(112, 112, 3)
(12544, 3)
[[ 9 24  6]
 [ 9 23  8]
 [10 24 11]
 ...
 [57 65 70]
 [51 59 64]
 [50 58 62]]
(112, 112, 3)
(12544, 3)
[[ 9 24  6]
 [ 9 23  8]
 [ 9 23 10]
 ...
 [51 59 63]
 [46 54 59]
 [57 65 70]]
(112, 112, 3)
(12544, 3)
[[ 9 23  8]
 [ 9 23  8]
 [10 24  9]
 ...
 [46 54 58]
 [50 58 63]
 [64 72 76]]
(112, 112, 3)
(12544, 3)
[[ 9 23  8]
 [ 9 23  8]
 [12 26 13]
 ...
 [47 55 59]
 [40 48 52]
 [38 46 50]]
(112, 112, 3)
(12544, 3)
[[ 9 23 10]
 [ 9 23  8]
 [13 26 16]
 ...
 [47 57 61]
 [25 35 39]
 [23 33 37]]
(112, 112, 3)
(12544, 3)
[[11 21 13]
 [13 24 13]
 [15 25 17]
 ...
 [52 65 68]
 [37 50 53]
 [35 48 51]]
(112, 112, 3)
(12544, 3)
[[11 21 13]
 [15 26 15]
 [17 28 17]
 ...
 [47 60 63]
 [41 54 57]
 [30 43 46]]
(112, 112, 3)
(12544, 3)
[[10 22 14]
 [11 23 15]
 [13 25 17]
 ...
 [48 61 64]
 [37 50 53]
 [23 36 39]]
(112, 112, 3)
(12544, 3)
[[10 22 14]
 [11 23 15]
 [12 24 16]
 ...
 [36 48 52]
 [31 44 47]
 [24 37 40]]
(112, 112, 3)
(12544, 3)
[[10 22 14]
 [11 23 15]
 [12 23 17]
 ...
 [32 42

(112, 112, 3)
(12544, 3)
[[235 241 222]
 [235 241 222]
 [235 241 222]
 ...
 [ 63 126 126]
 [ 70 130 130]
 [ 73 130 132]]
(112, 112, 3)
(12544, 3)
[[235 241 222]
 [235 241 222]
 [235 241 222]
 ...
 [ 63 126 126]
 [ 69 129 129]
 [ 73 131 133]]
(112, 112, 3)
(12544, 3)
[[235 241 222]
 [235 241 222]
 [235 241 222]
 ...
 [ 63 126 126]
 [ 69 129 129]
 [ 73 131 133]]
(112, 112, 3)
(12544, 3)
[[235 241 222]
 [235 241 222]
 [235 241 222]
 ...
 [ 63 126 126]
 [ 69 129 129]
 [ 73 131 133]]
(112, 112, 3)
(12544, 3)
[[235 241 222]
 [235 241 222]
 [235 241 222]
 ...
 [ 62 125 125]
 [ 68 128 129]
 [ 74 131 133]]
(112, 112, 3)
(12544, 3)
[[235 241 222]
 [235 241 222]
 [235 241 222]
 ...
 [ 64 127 127]
 [ 68 128 129]
 [ 72 130 132]]
(112, 112, 3)
(12544, 3)
[[134 133 122]
 [143 145 129]
 [140 145 129]
 ...
 [249 218 177]
 [245 208 176]
 [241 205 178]]
(112, 112, 3)
(12544, 3)
[[134 133 122]
 [143 145 129]
 [140 145 129]
 ...
 [249 217 177]
 [246 209 177]
 [240 204 177]]
(112, 112, 3)
(12544, 3)
[[132 1

(112, 112, 3)
(12544, 3)
[[160 177 175]
 [ 86 103 101]
 [162 177 175]
 ...
 [ 29  59  59]
 [ 29  60  62]
 [ 30  61  66]]
(112, 112, 3)
(12544, 3)
[[226 243 241]
 [ 41  58  56]
 [217 231 229]
 ...
 [ 33  59  60]
 [ 31  60  62]
 [ 34  59  65]]
(112, 112, 3)
(12544, 3)
[[226 243 241]
 [ 41  58  56]
 [217 231 229]
 ...
 [ 33  59  60]
 [ 31  60  62]
 [ 34  59  65]]
(112, 112, 3)
(12544, 3)
[[217 234 232]
 [ 51  68  66]
 [227 241 239]
 ...
 [ 34  60  61]
 [ 33  58  61]
 [ 33  57  64]]
(112, 112, 3)
(12544, 3)
[[217 234 232]
 [ 41  58  56]
 [225 240 238]
 ...
 [ 34  60  61]
 [ 33  58  61]
 [ 33  57  64]]
(112, 112, 3)
(12544, 3)
[[183 200 198]
 [ 68  85  83]
 [190 207 205]
 ...
 [ 33  62  62]
 [ 31  60  62]
 [ 31  58  63]]
(112, 112, 3)
(12544, 3)
[[165 182 180]
 [ 75  92  90]
 [177 194 192]
 ...
 [ 30  58  61]
 [ 31  60  62]
 [ 33  61  66]]
(112, 112, 3)
(12544, 3)
[[199 216 214]
 [ 50  67  65]
 [203 220 218]
 ...
 [ 30  58  61]
 [ 31  59  62]
 [ 33  61  66]]
(112, 112, 3)
(12544, 3)
[[199 2

(112, 112, 3)
(12544, 3)
[[250 250 250]
 [250 250 250]
 [250 250 250]
 ...
 [ 64 110  19]
 [ 67 112  16]
 [ 68 105  17]]
(112, 112, 3)
(12544, 3)
[[250 250 250]
 [250 250 250]
 [250 250 250]
 ...
 [ 86 134  45]
 [ 89 135  42]
 [ 89 126  38]]
(112, 112, 3)
(12544, 3)
[[250 250 250]
 [250 250 250]
 [250 250 250]
 ...
 [109 159  87]
 [ 73 121  37]
 [ 84 130  40]]
(112, 112, 3)
(12544, 3)
[[250 250 250]
 [250 250 250]
 [250 250 250]
 ...
 [125 176 114]
 [ 81 128  53]
 [ 81 128  40]]
(112, 112, 3)
(12544, 3)
[[250 250 250]
 [250 250 250]
 [250 250 250]
 ...
 [140 188 129]
 [ 97 148  74]
 [ 90 140  54]]
(112, 112, 3)
(12544, 3)
[[250 250 250]
 [250 250 250]
 [250 250 250]
 ...
 [124 172 113]
 [117 167  96]
 [ 86 137  57]]
(112, 112, 3)
(12544, 3)
[[233 232 226]
 [217 216 210]
 [117 116 110]
 ...
 [ 59  52  44]
 [ 59  52  44]
 [ 81  72  64]]
(112, 112, 3)
(12544, 3)
[[233 232 226]
 [217 216 210]
 [117 116 110]
 ...
 [ 58  51  43]
 [ 62  54  46]
 [ 82  73  65]]
(112, 112, 3)
(12544, 3)
[[233 2

(112, 112, 3)
(12544, 3)
[[238 220 191]
 [235 217 188]
 [234 216 187]
 ...
 [ 46 127  87]
 [ 44 124  87]
 [ 38 112  80]]
(112, 112, 3)
(12544, 3)
[[235 218 187]
 [234 217 186]
 [234 217 186]
 ...
 [ 46 126  89]
 [ 44 124  87]
 [ 37 114  79]]
(112, 112, 3)
(12544, 3)
[[235 218 187]
 [234 217 186]
 [234 217 186]
 ...
 [ 46 126  89]
 [ 44 124  87]
 [ 37 114  79]]
(112, 112, 3)
(12544, 3)
[[235 218 187]
 [234 217 186]
 [234 217 186]
 ...
 [ 46 126  89]
 [ 44 124  87]
 [ 37 114  79]]
(112, 112, 3)
(12544, 3)
[[235 219 182]
 [233 217 183]
 [234 218 183]
 ...
 [ 44 127  89]
 [ 43 125  88]
 [ 40 114  79]]
(112, 112, 3)
(12544, 3)
[[234 218 184]
 [233 216 185]
 [234 217 186]
 ...
 [ 45 128  90]
 [ 43 125  88]
 [ 40 113  79]]
(112, 112, 3)
(12544, 3)
[[235 219 185]
 [234 217 186]
 [234 217 186]
 ...
 [ 45 128  90]
 [ 43 125  88]
 [ 40 113  79]]
(112, 112, 3)
(12544, 3)
[[235 219 185]
 [234 217 186]
 [234 217 186]
 ...
 [ 45 128  90]
 [ 44 126  88]
 [ 40 114  79]]
(112, 112, 3)
(12544, 3)
[[235 2

(112, 112, 3)
(12544, 3)
[[ 42  66  57]
 [137 164 156]
 [114 140 131]
 ...
 [ 55 143 102]
 [ 53 141 100]
 [ 53 141 100]]
(112, 112, 3)
(12544, 3)
[[ 43  68  55]
 [136 163 153]
 [113 140 129]
 ...
 [ 52 140  99]
 [ 53 141 100]
 [ 53 141 100]]
(112, 112, 3)
(12544, 3)
[[ 41  63  51]
 [121 146 136]
 [136 160 150]
 ...
 [ 53 142 101]
 [ 54 142 101]
 [ 54 143 102]]
(112, 112, 3)
(12544, 3)
[[ 45  64  55]
 [122 147 138]
 [132 157 154]
 ...
 [ 49 140  98]
 [ 52 143 101]
 [ 51 142 100]]
(112, 112, 3)
(12544, 3)
[[ 34  55  45]
 [106 136 126]
 [135 162 161]
 ...
 [ 49 140  98]
 [ 52 143 101]
 [ 49 140  98]]
(112, 112, 3)
(12544, 3)
[[ 35  57  47]
 [110 140 130]
 [138 165 164]
 ...
 [ 48 139  97]
 [ 50 141  99]
 [ 48 139  97]]
(112, 112, 3)
(12544, 3)
[[ 42  64  54]
 [100 130 121]
 [141 168 167]
 ...
 [ 48 139  97]
 [ 50 141  99]
 [ 48 139  97]]
(112, 112, 3)
(12544, 3)
[[121 135 120]
 [116 130 115]
 [110 124 109]
 ...
 [100 124 109]
 [ 99 123 108]
 [100 124 109]]
(112, 112, 3)
(12544, 3)
[[121 1

[[176 173 172]
 [ 29  22  22]
 [130 122 122]
 ...
 [ 65  58  45]
 [ 66  59  44]
 [ 68  61  46]]
(112, 112, 3)
(12544, 3)
[[176 173 172]
 [ 31  23  23]
 [128 120 120]
 ...
 [ 65  58  45]
 [ 66  59  44]
 [ 68  61  46]]
(112, 112, 3)
(12544, 3)
[[173 170 169]
 [ 30  22  22]
 [125 117 117]
 ...
 [ 67  60  45]
 [ 65  58  44]
 [ 64  57  44]]
(112, 112, 3)
(12544, 3)
[[168 165 164]
 [ 27  20  19]
 [116 108 108]
 ...
 [ 67  60  47]
 [ 65  58  44]
 [ 63  56  43]]
(112, 112, 3)
(12544, 3)
[[167 164 163]
 [ 27  20  19]
 [118 110 110]
 ...
 [ 66  59  46]
 [ 64  57  43]
 [ 62  55  43]]
(112, 112, 3)
(12544, 3)
[[164 161 160]
 [ 26  18  18]
 [117 109 109]
 ...
 [ 67  60  47]
 [ 62  55  43]
 [ 62  55  43]]
(112, 112, 3)
(12544, 3)
[[166 163 162]
 [ 26  18  18]
 [117 109 109]
 ...
 [ 68  61  47]
 [ 63  56  43]
 [ 64  57  43]]
(112, 112, 3)
(12544, 3)
[[165 163 159]
 [ 26  20  17]
 [116 109 106]
 ...
 [ 68  61  46]
 [ 63  56  43]
 [ 63  56  43]]
(112, 112, 3)
(12544, 3)
[[165 163 159]
 [ 26  20  17]
 [

(112, 112, 3)
(12544, 3)
[[246 246 244]
 [246 246 244]
 [246 246 244]
 ...
 [149 163 163]
 [143 159 159]
 [136 163 159]]
(112, 112, 3)
(12544, 3)
[[246 246 244]
 [248 248 246]
 [248 248 246]
 ...
 [131 150 147]
 [133 153 150]
 [141 158 156]]
(112, 112, 3)
(12544, 3)
[[246 246 244]
 [248 248 246]
 [248 248 246]
 ...
 [134 151 149]
 [132 149 147]
 [130 147 145]]
(112, 112, 3)
(12544, 3)
[[ 68  73  73]
 [ 49  54  54]
 [ 94  99  99]
 ...
 [106 145 184]
 [105 144 183]
 [105 144 183]]
(112, 112, 3)
(12544, 3)
[[ 96 101 101]
 [ 70  75  75]
 [118 123 123]
 ...
 [107 146 185]
 [106 145 184]
 [105 144 183]]
(112, 112, 3)
(12544, 3)
[[147 152 152]
 [113 118 118]
 [168 173 173]
 ...
 [106 145 184]
 [105 144 183]
 [104 143 182]]
(112, 112, 3)
(12544, 3)
[[175 180 180]
 [164 169 169]
 [181 186 186]
 ...
 [107 145 184]
 [106 145 184]
 [104 143 182]]
(112, 112, 3)
(12544, 3)
[[182 185 185]
 [186 189 189]
 [150 153 153]
 ...
 [107 146 185]
 [106 145 184]
 [104 143 182]]
(112, 112, 3)
(12544, 3)
[[174 1

(112, 112, 3)
(12544, 3)
[[88 84 46]
 [97 91 54]
 [91 84 47]
 ...
 [87 88 83]
 [85 86 81]
 [81 82 77]]
(112, 112, 3)
(12544, 3)
[[81 77 39]
 [98 91 54]
 [97 89 53]
 ...
 [85 86 81]
 [82 83 78]
 [79 80 75]]
(112, 112, 3)
(12544, 3)
[[79 75 37]
 [99 92 55]
 [93 86 49]
 ...
 [88 89 84]
 [87 88 83]
 [77 78 73]]
(112, 112, 3)
(12544, 3)
[[196 224 236]
 [203 222 236]
 [204 222 236]
 ...
 [ 33  46   0]
 [ 56  70  28]
 [ 32  45   3]]
(112, 112, 3)
(12544, 3)
[[196 224 236]
 [203 222 236]
 [204 222 236]
 ...
 [ 32  45   0]
 [ 56  70  28]
 [ 29  42   1]]
(112, 112, 3)
(12544, 3)
[[198 224 236]
 [204 222 236]
 [203 224 237]
 ...
 [ 43  58   6]
 [ 45  58  19]
 [ 30  42   6]]
(112, 112, 3)
(12544, 3)
[[200 223 236]
 [202 223 236]
 [202 225 238]
 ...
 [ 45  59  15]
 [ 53  65  29]
 [ 29  40   6]]
(112, 112, 3)
(12544, 3)
[[200 223 236]
 [202 223 236]
 [204 225 238]
 ...
 [ 42  56  12]
 [ 51  63  27]
 [ 32  43   9]]
(112, 112, 3)
(12544, 3)
[[200 223 236]
 [202 223 236]
 [204 225 238]
 ...
 [ 39  52  

(112, 112, 3)
(12544, 3)
[[234 225 209]
 [236 229 213]
 [240 230 216]
 ...
 [ 58 142 108]
 [ 58 142 108]
 [ 58 142 108]]
(112, 112, 3)
(12544, 3)
[[226 227 214]
 [228 227 214]
 [228 227 216]
 ...
 [ 58 142 108]
 [ 58 142 108]
 [ 58 142 108]]
(112, 112, 3)
(12544, 3)
[[226 227 214]
 [228 227 214]
 [228 227 216]
 ...
 [ 58 142 108]
 [ 58 142 108]
 [ 58 142 108]]
(112, 112, 3)
(12544, 3)
[[231 228 213]
 [231 227 214]
 [230 226 214]
 ...
 [ 58 142 108]
 [ 58 142 108]
 [ 58 142 108]]
(112, 112, 3)
(12544, 3)
[[233 229 217]
 [227 227 216]
 [223 228 216]
 ...
 [ 59 143 109]
 [ 59 143 109]
 [ 59 143 109]]
(112, 112, 3)
(12544, 3)
[[222 229 216]
 [218 227 215]
 [215 227 216]
 ...
 [ 58 142 108]
 [ 58 142 108]
 [ 58 142 108]]
(112, 112, 3)
(12544, 3)
[[230 224 214]
 [228 223 213]
 [226 225 214]
 ...
 [ 57 141 107]
 [ 57 141 107]
 [ 57 141 107]]
(112, 112, 3)
(12544, 3)
[[225 225 214]
 [224 225 214]
 [223 228 215]
 ...
 [ 56 140 106]
 [ 56 140 106]
 [ 56 140 106]]
(112, 112, 3)
(12544, 3)
[[224 2

(112, 112, 3)
(12544, 3)
[[175 235 231]
 [126 190 165]
 [110 169 135]
 ...
 [ 69  85  78]
 [ 79  97  90]
 [ 69  86  85]]
(112, 112, 3)
(12544, 3)
[[175 235 231]
 [126 190 165]
 [110 169 135]
 ...
 [ 69  85  78]
 [ 79  97  90]
 [ 69  86  85]]
(112, 112, 3)
(12544, 3)
[[175 235 231]
 [126 190 165]
 [110 169 135]
 ...
 [ 69  85  78]
 [ 79  97  90]
 [ 69  86  85]]
(112, 112, 3)
(12544, 3)
[[175 235 231]
 [126 190 165]
 [110 169 135]
 ...
 [ 69  85  78]
 [ 79  97  90]
 [ 69  86  85]]
(112, 112, 3)
(12544, 3)
[[175 235 231]
 [126 190 165]
 [110 169 135]
 ...
 [ 69  85  78]
 [ 79  97  90]
 [ 69  86  85]]
(112, 112, 3)
(12544, 3)
[[175 235 231]
 [126 190 165]
 [110 169 135]
 ...
 [ 69  85  78]
 [ 79  97  90]
 [ 69  86  85]]
(112, 112, 3)
(12544, 3)
[[174 235 231]
 [121 187 162]
 [107 170 134]
 ...
 [ 70  86  78]
 [ 79  97  90]
 [ 69  86  85]]
(112, 112, 3)
(12544, 3)
[[174 235 231]
 [121 187 162]
 [107 170 134]
 ...
 [ 70  86  78]
 [ 79  97  90]
 [ 69  86  85]]
(112, 112, 3)
(12544, 3)
[[174 2

(112, 112, 3)
(12544, 3)
[[ 36  80  57]
 [ 34  78  55]
 [ 34  79  55]
 ...
 [117 132 135]
 [116 131 134]
 [116 131 134]]
(112, 112, 3)
(12544, 3)
[[  4  48  30]
 [  0  32  14]
 [  5  33  16]
 ...
 [128 141 146]
 [128 142 147]
 [128 138 147]]
(112, 112, 3)
(12544, 3)
[[  5  49  31]
 [  0  32  14]
 [  4  32  15]
 ...
 [128 141 146]
 [128 142 147]
 [128 138 147]]
(112, 112, 3)
(12544, 3)
[[ 31  34  23]
 [ 31  34  23]
 [ 31  35  23]
 ...
 [129 142 145]
 [128 143 146]
 [127 145 147]]
(112, 112, 3)
(12544, 3)
[[ 31  34  23]
 [ 31  34  23]
 [ 31  34  23]
 ...
 [129 142 145]
 [130 143 146]
 [129 144 147]]
(112, 112, 3)
(12544, 3)
[[ 24  28  14]
 [ 24  28  14]
 [ 24  28  14]
 ...
 [129 144 147]
 [129 144 147]
 [129 143 148]]
(112, 112, 3)
(12544, 3)
[[ 24  28  14]
 [ 24  28  14]
 [ 24  28  14]
 ...
 [130 145 148]
 [130 144 148]
 [130 144 149]]
(112, 112, 3)
(12544, 3)
[[ 22  28  16]
 [ 22  28  16]
 [ 24  30  18]
 ...
 [132 146 146]
 [132 146 146]
 [131 144 147]]
(112, 112, 3)
(12544, 3)
[[ 23  

(112, 112, 3)
(12544, 3)
[[ 15  23  47]
 [ 14  22  46]
 [ 11  19  43]
 ...
 [ 53  72  93]
 [ 72  92 112]
 [ 63  83 103]]
(112, 112, 3)
(12544, 3)
[[ 15  23  47]
 [ 14  22  46]
 [ 11  19  43]
 ...
 [ 53  72  93]
 [ 72  92 112]
 [ 63  83 103]]
(112, 112, 3)
(12544, 3)
[[ 15  23  47]
 [ 14  22  46]
 [ 11  19  43]
 ...
 [ 53  73  93]
 [ 72  92 112]
 [ 63  83 103]]
(112, 112, 3)
(12544, 3)
[[ 15  23  47]
 [ 12  20  44]
 [ 11  19  43]
 ...
 [ 53  73  93]
 [ 72  92 112]
 [ 63  83 103]]
(112, 112, 3)
(12544, 3)
[[ 15  22  49]
 [ 14  22  47]
 [ 11  19  43]
 ...
 [ 51  71  91]
 [ 72  92 112]
 [ 64  84 104]]
(112, 112, 3)
(12544, 3)
[[ 14  22  46]
 [ 12  20  42]
 [ 11  19  41]
 ...
 [ 51  71  91]
 [ 72  92 112]
 [ 64  84 104]]
(112, 112, 3)
(12544, 3)
[[ 15  23  47]
 [ 14  22  45]
 [ 11  19  41]
 ...
 [ 51  71  92]
 [ 74  94 114]
 [ 64  84 104]]
(112, 112, 3)
(12544, 3)
[[ 15  23  47]
 [ 12  20  42]
 [ 10  18  40]
 ...
 [ 51  71  92]
 [ 74  94 114]
 [ 64  84 104]]
(112, 112, 3)
(12544, 3)
[[ 15  

(112, 112, 3)
(12544, 3)
[[216 216 216]
 [216 216 216]
 [216 216 216]
 ...
 [ 78 143 194]
 [ 68 133 184]
 [ 92 157 208]]
(112, 112, 3)
(12544, 3)
[[216 216 216]
 [216 216 216]
 [216 216 216]
 ...
 [ 78 143 194]
 [ 68 133 184]
 [ 92 157 208]]
(112, 112, 3)
(12544, 3)
[[216 216 216]
 [216 216 216]
 [216 216 216]
 ...
 [ 78 143 194]
 [ 68 133 184]
 [ 92 157 208]]
(112, 112, 3)
(12544, 3)
[[216 216 216]
 [216 216 216]
 [216 216 216]
 ...
 [ 78 143 194]
 [ 68 133 184]
 [ 92 157 208]]
(112, 112, 3)
(12544, 3)
[[216 216 216]
 [216 216 216]
 [216 216 216]
 ...
 [ 78 143 192]
 [ 68 133 182]
 [ 92 157 206]]
(112, 112, 3)
(12544, 3)
[[216 216 216]
 [216 216 216]
 [216 216 216]
 ...
 [ 78 143 192]
 [ 68 133 182]
 [ 92 157 206]]
(112, 112, 3)
(12544, 3)
[[216 216 216]
 [216 216 216]
 [216 216 216]
 ...
 [ 78 143 192]
 [ 68 133 182]
 [ 92 157 206]]
(112, 112, 3)
(12544, 3)
[[216 216 216]
 [216 216 216]
 [216 216 216]
 ...
 [ 78 143 192]
 [ 68 133 182]
 [ 92 157 206]]
(112, 112, 3)
(12544, 3)
[[216 2

(112, 112, 3)
(12544, 3)
[[51 43 38]
 [56 50 45]
 [61 58 52]
 ...
 [49 38 35]
 [84 64 61]
 [60 29 26]]
(112, 112, 3)
(12544, 3)
[[51 43 38]
 [56 50 45]
 [61 58 52]
 ...
 [49 38 35]
 [84 64 61]
 [60 29 26]]
(112, 112, 3)
(12544, 3)
[[49 41 36]
 [54 48 43]
 [57 55 49]
 ...
 [49 38 35]
 [84 64 61]
 [60 29 26]]
(112, 112, 3)
(12544, 3)
[[48 40 35]
 [53 47 42]
 [57 54 48]
 ...
 [45 39 36]
 [79 64 60]
 [56 28 24]]
(112, 112, 3)
(12544, 3)
[[48 40 35]
 [53 47 42]
 [57 54 48]
 ...
 [45 39 36]
 [79 64 60]
 [56 28 24]]
(112, 112, 3)
(12544, 3)
[[48 40 35]
 [53 47 42]
 [57 54 48]
 ...
 [45 39 36]
 [79 64 60]
 [56 28 24]]
(112, 112, 3)
(12544, 3)
[[47 38 33]
 [54 48 43]
 [55 52 46]
 ...
 [46 37 35]
 [82 66 62]
 [56 28 24]]
(112, 112, 3)
(12544, 3)
[[47 38 33]
 [54 48 43]
 [55 52 46]
 ...
 [45 38 35]
 [80 66 62]
 [54 29 24]]
(112, 112, 3)
(12544, 3)
[[50 40 35]
 [56 48 43]
 [56 50 45]
 ...
 [44 40 37]
 [77 66 61]
 [50 27 23]]
(112, 112, 3)
(12544, 3)
[[51 41 36]
 [57 49 44]
 [56 50 45]
 ...
 [51 44

(112, 112, 3)
(12544, 3)
[[247 252 247]
 [250 254 249]
 [249 253 248]
 ...
 [229 220 224]
 [229 220 224]
 [228 219 223]]
(112, 112, 3)
(12544, 3)
[[247 252 247]
 [250 254 249]
 [249 253 248]
 ...
 [229 220 224]
 [229 220 224]
 [228 219 223]]
(112, 112, 3)
(12544, 3)
[[252 252 250]
 [251 251 249]
 [253 253 251]
 ...
 [224 216 218]
 [224 216 218]
 [224 216 218]]
(112, 112, 3)
(12544, 3)
[[252 252 252]
 [253 253 253]
 [252 252 252]
 ...
 [224 216 218]
 [224 216 218]
 [224 216 218]]
(112, 112, 3)
(12544, 3)
[[251 251 251]
 [251 251 251]
 [253 253 253]
 ...
 [223 215 217]
 [223 215 217]
 [223 215 217]]
(112, 112, 3)
(12544, 3)
[[251 251 251]
 [251 251 251]
 [252 252 252]
 ...
 [223 215 217]
 [223 215 217]
 [223 215 217]]
(112, 112, 3)
(12544, 3)
[[250 250 250]
 [250 250 250]
 [250 250 250]
 ...
 [221 213 215]
 [221 213 215]
 [221 213 215]]
(112, 112, 3)
(12544, 3)
[[252 251 253]
 [251 250 253]
 [253 252 254]
 ...
 [222 214 216]
 [222 214 216]
 [222 214 216]]
(112, 112, 3)
(12544, 3)
[[251 2

(112, 112, 3)
(12544, 3)
[[ 68  93  80]
 [ 69 101  83]
 [ 80 113  90]
 ...
 [102 107  97]
 [102 107  97]
 [ 97 108  97]]
(112, 112, 3)
(12544, 3)
[[ 72  92  80]
 [ 73 100  83]
 [ 84 111  90]
 ...
 [ 95 109  95]
 [ 92 111  97]
 [ 90 111  97]]
(112, 112, 3)
(12544, 3)
[[ 73  93  81]
 [ 69 101  83]
 [ 77 113  90]
 ...
 [ 95 107  97]
 [ 89 110  98]
 [ 85 111  98]]
(112, 112, 3)
(12544, 3)
[[ 82  92  81]
 [ 73 100  83]
 [ 78 113  91]
 ...
 [100 104 100]
 [ 97 108  99]
 [ 96 109  98]]
(112, 112, 3)
(12544, 3)
[[ 80  93  82]
 [ 75 100  82]
 [ 83 109  89]
 ...
 [103 111 104]
 [ 95 110  99]
 [ 96 109  96]]
(112, 112, 3)
(12544, 3)
[[ 82  93  82]
 [ 75 100  82]
 [ 80 109  89]
 ...
 [ 92 116 101]
 [ 87 113  96]
 [ 90 111  92]]
(112, 112, 3)
(12544, 3)
[[ 85  92  79]
 [ 84  94  81]
 [ 86 105  90]
 ...
 [ 94 115 101]
 [ 90 116 101]
 [ 96 109  96]]
(112, 112, 3)
(12544, 3)
[[ 81  93  79]
 [ 80  94  81]
 [ 82 106  90]
 ...
 [101 114  99]
 [ 95 115  99]
 [ 98 109  94]]
(112, 112, 3)
(12544, 3)
[[ 70  

(112, 112, 3)
(12544, 3)
[[140 134 127]
 [ 53  55  47]
 [ 46  51  38]
 ...
 [ 26  58  44]
 [ 13  50  35]
 [ 20  60  45]]
(112, 112, 3)
(12544, 3)
[[140 134 127]
 [ 53  55  47]
 [ 46  51  38]
 ...
 [ 26  58  44]
 [ 13  50  35]
 [ 20  60  45]]
(112, 112, 3)
(12544, 3)
[[139 134 126]
 [ 53  55  47]
 [ 46  51  38]
 ...
 [ 24  53  42]
 [ 14  45  34]
 [ 19  55  43]]
(112, 112, 3)
(12544, 3)
[[139 133 126]
 [ 54  55  47]
 [ 47  51  39]
 ...
 [ 27  60  45]
 [ 17  53  38]
 [ 19  58  43]]
(112, 112, 3)
(12544, 3)
[[142 135 126]
 [ 58  58  48]
 [ 48  50  36]
 ...
 [ 26  58  44]
 [ 16  51  36]
 [ 19  57  42]]
(112, 112, 3)
(12544, 3)
[[140 134 127]
 [ 61  59  50]
 [ 50  49  35]
 ...
 [ 26  58  44]
 [ 16  51  36]
 [ 19  57  42]]
(112, 112, 3)
(12544, 3)
[[143 138 130]
 [ 70  69  58]
 [ 50  48  39]
 ...
 [ 25  57  43]
 [ 16  51  36]
 [ 19  57  42]]
(112, 112, 3)
(12544, 3)
[[144 141 126]
 [ 78  78  64]
 [ 49  47  38]
 ...
 [ 24  55  44]
 [ 19  54  39]
 [ 17  54  39]]
(112, 112, 3)
(12544, 3)
[[145 1

(112, 112, 3)
(12544, 3)
[[130 169 108]
 [100 153  93]
 [ 72 126  67]
 ...
 [133 192 125]
 [133 192 125]
 [133 192 125]]
(112, 112, 3)
(12544, 3)
[[130 169 108]
 [100 153  93]
 [ 72 126  67]
 ...
 [133 192 125]
 [133 192 125]
 [133 192 125]]
(112, 112, 3)
(12544, 3)
[[130 169 108]
 [100 153  93]
 [ 72 126  67]
 ...
 [133 192 125]
 [133 192 125]
 [133 192 125]]
(112, 112, 3)
(12544, 3)
[[130 169 108]
 [100 153  93]
 [ 72 126  67]
 ...
 [133 192 125]
 [133 192 125]
 [133 192 125]]
(112, 112, 3)
(12544, 3)
[[130 169 108]
 [100 153  93]
 [ 72 126  67]
 ...
 [133 192 125]
 [133 192 125]
 [133 192 125]]
(112, 112, 3)
(12544, 3)
[[130 169 108]
 [100 153  93]
 [ 72 126  67]
 ...
 [133 192 125]
 [133 192 125]
 [133 192 125]]
(112, 112, 3)
(12544, 3)
[[131 167 107]
 [103 153  93]
 [ 75 126  68]
 ...
 [134 192 128]
 [134 192 128]
 [134 192 128]]
(112, 112, 3)
(12544, 3)
[[132 168 108]
 [103 153  93]
 [ 74 125  67]
 ...
 [134 192 128]
 [134 192 128]
 [134 192 128]]
(112, 112, 3)
(12544, 3)
[[130 1

(112, 112, 3)
(12544, 3)
[[246 245 247]
 [250 249 251]
 [245 244 246]
 ...
 [ 84 136 110]
 [ 83 135 109]
 [ 83 135 109]]
(112, 112, 3)
(12544, 3)
[[249 249 249]
 [248 246 248]
 [249 247 249]
 ...
 [ 83 140 113]
 [ 81 138 111]
 [ 81 138 111]]
(112, 112, 3)
(12544, 3)
[[250 249 249]
 [248 246 248]
 [244 243 244]
 ...
 [ 87 144 117]
 [ 86 143 116]
 [ 85 142 115]]
(112, 112, 3)
(12544, 3)
[[251 249 252]
 [247 246 248]
 [246 244 249]
 ...
 [ 90 144 118]
 [ 90 145 119]
 [ 89 143 117]]
(112, 112, 3)
(12544, 3)
[[245 244 246]
 [247 246 248]
 [250 247 253]
 ...
 [ 87 141 115]
 [ 88 142 116]
 [ 88 142 116]]
(112, 112, 3)
(12544, 3)
[[242 241 244]
 [250 248 253]
 [247 245 251]
 ...
 [ 80 135 109]
 [ 80 134 108]
 [ 87 141 115]]
(112, 112, 3)
(12544, 3)
[[243 242 245]
 [250 248 251]
 [245 244 246]
 ...
 [ 79 133 107]
 [ 77 131 105]
 [ 84 138 112]]
(112, 112, 3)
(12544, 3)
[[244 243 246]
 [251 250 252]
 [247 246 248]
 ...
 [ 72 124  98]
 [ 71 123  97]
 [ 76 128 102]]
(112, 112, 3)
(12544, 3)
[[248 2

(112, 112, 3)
(12544, 3)
[[246 247 249]
 [245 247 249]
 [249 247 249]
 ...
 [ 34  72  94]
 [ 32  70  92]
 [ 38  76  97]]
(112, 112, 3)
(12544, 3)
[[248 245 251]
 [247 244 250]
 [245 242 248]
 ...
 [ 35  72  96]
 [ 31  68  92]
 [ 34  71  95]]
(112, 112, 3)
(12544, 3)
[[243 248 246]
 [245 248 248]
 [245 247 249]
 ...
 [ 35  70  99]
 [ 31  66  95]
 [ 34  69  98]]
(112, 112, 3)
(12544, 3)
[[248 249 244]
 [248 249 244]
 [248 249 244]
 ...
 [ 37  72 101]
 [ 35  70  99]
 [ 34  69  98]]
(112, 112, 3)
(12544, 3)
[[13 17  3]
 [21 24  3]
 [26 24  1]
 ...
 [ 7 10  0]
 [10 13  3]
 [ 8 10  3]]
(112, 112, 3)
(12544, 3)
[[12 16  2]
 [20 23  1]
 [23 20  0]
 ...
 [ 9 12  2]
 [ 8 11  1]
 [ 8 10  3]]
(112, 112, 3)
(12544, 3)
[[21 20  7]
 [28 24  3]
 [30 21  0]
 ...
 [ 9 12  2]
 [ 8 10  3]
 [ 7  9  2]]
(112, 112, 3)
(12544, 3)
[[28 20  8]
 [33 25  5]
 [29 19  0]
 ...
 [ 8 11  1]
 [ 6  8  1]
 [ 6  8  1]]
(112, 112, 3)
(12544, 3)
[[37 26 18]
 [40 27 10]
 [37 21  1]
 ...
 [ 8 11  1]
 [ 6  8  1]
 [ 6  8  1]]
(

(112, 112, 3)
(12544, 3)
[[148 173 193]
 [171 195 219]
 [162 184 216]
 ...
 [151 151 151]
 [151 151 151]
 [151 151 151]]
(112, 112, 3)
(12544, 3)
[[148 173 193]
 [171 195 219]
 [163 185 216]
 ...
 [151 151 151]
 [151 151 151]
 [151 151 151]]
(112, 112, 3)
(12544, 3)
[[147 173 192]
 [171 195 219]
 [164 187 218]
 ...
 [151 151 151]
 [151 151 151]
 [151 151 151]]
(112, 112, 3)
(12544, 3)
[[159 185 206]
 [170 192 220]
 [166 191 224]
 ...
 [151 151 151]
 [151 151 151]
 [151 151 151]]
(112, 112, 3)
(12544, 3)
[[158 184 206]
 [170 193 221]
 [166 191 225]
 ...
 [151 151 151]
 [151 151 151]
 [151 151 151]]
(112, 112, 3)
(12544, 3)
[[156 183 208]
 [168 192 222]
 [164 191 227]
 ...
 [151 151 151]
 [151 151 151]
 [151 151 151]]
(112, 112, 3)
(12544, 3)
[[156 183 208]
 [168 192 222]
 [164 191 227]
 ...
 [151 151 151]
 [151 151 151]
 [151 151 151]]
(112, 112, 3)
(12544, 3)
[[161 188 213]
 [167 190 220]
 [162 189 224]
 ...
 [147 146 148]
 [147 146 148]
 [147 146 148]]
(112, 112, 3)
(12544, 3)
[[161 1

(112, 112, 3)
(12544, 3)
[[48 53 46]
 [51 56 49]
 [54 59 52]
 ...
 [79 76 55]
 [40 35 21]
 [37 33 23]]
(112, 112, 3)
(12544, 3)
[[129 129 129]
 [112 112 112]
 [ 95  95  95]
 ...
 [ 64  75  66]
 [ 71  81  75]
 [ 80  77  76]]
(112, 112, 3)
(12544, 3)
[[129 129 129]
 [112 112 112]
 [ 95  95  95]
 ...
 [ 64  75  66]
 [ 71  81  75]
 [ 80  77  76]]
(112, 112, 3)
(12544, 3)
[[126 126 126]
 [104 104 104]
 [ 97  97  97]
 ...
 [ 64  72  65]
 [ 70  79  73]
 [ 80  79  77]]
(112, 112, 3)
(12544, 3)
[[117 117 117]
 [ 99  99  99]
 [103 103 103]
 ...
 [ 65  79  67]
 [ 67  78  72]
 [ 77  80  80]]
(112, 112, 3)
(12544, 3)
[[118 118 118]
 [100 100 100]
 [104 104 104]
 ...
 [ 68  80  67]
 [ 67  79  69]
 [ 75  81  76]]
(112, 112, 3)
(12544, 3)
[[125 125 125]
 [ 99  99  99]
 [109 109 109]
 ...
 [ 65  78  67]
 [ 71  80  72]
 [ 83  83  81]]
(112, 112, 3)
(12544, 3)
[[127 127 127]
 [ 99  99  99]
 [110 110 110]
 ...
 [ 67  81  66]
 [ 71  82  70]
 [ 85  83  86]]
(112, 112, 3)
(12544, 3)
[[129 129 129]
 [ 98  98 

(
   93.3131
  107.5407
  105.2729
 [torch.FloatTensor of size 3], 
  56.1015
  54.7933
  55.3897
 [torch.FloatTensor of size 3])

In [404]:
i = 0
for x in valid_dataset:
    #print(x)
    #if i == 100:
    #print(x)
    break
    

pose0 
(0 ,.,.) = 

Columns 0 to 6 
    73.2988   73.1375   75.1579   75.1575   85.1226   85.1210   81.2326
   85.9737   82.8679   87.3984   87.3984   85.7549   85.7581   76.3919
   78.9094   78.9198   77.2249   77.2266   80.0737   80.0678   74.1840
   89.2000   89.7714   89.7714   89.7714  100.6286  100.6286   99.4857
   52.5143   52.5143   52.5143   52.5143   59.3714   64.5143   64.5143
  100.9143  100.9143  103.2000  103.2000  103.2000  100.3429   93.4858
   77.0857   79.3711   81.6572   81.6572   81.0857   81.0857   73.0857
   79.0161   71.7272   70.5931   70.5938   99.8437   99.8411  115.2831
   35.4909   32.6325   32.5019   32.4997   39.5206   52.0288   55.4611
  108.5010  114.2172  121.6837  121.6854  127.5623  128.8135  122.5601
   59.1240   60.3645   59.3239   59.3240   65.2265   68.6559   73.5048
   36.5838   35.3158   32.9698   32.9401   68.6881   82.3877   89.8667
   33.0639   30.7856   24.8418   24.8338   69.0412   76.1817   87.1440
  133.4709  135.1547  136.1002  136.0993

In [25]:
train_loader = torch.utils.data.DataLoader(train_dataset,
    batch_size=10, shuffle=True)
    #num_workers=2, pin_memory=True) 

In [409]:
valid_loader = torch.utils.data.DataLoader(valid_dataset,
    batch_size=5, shuffle=True)
    #num_workers=2, pin_memory=True)

In [410]:
for x in valid_loader:
    # transpose 
    print(x[0].transpose(4,3).transpose(3,2).transpose(2,1).size())
    for t in x[1:]:
        print(t.size())
    
    break

torch.Size([5, 3, 15, 112, 112])
torch.Size([5, 1])
torch.Size([5, 112, 112, 15])
torch.Size([5, 2, 15, 15])
torch.Size([5, 15])


## Model

In [0]:
class C3D(nn.Module):
    """
    The C3D network as described in [1].
    """

    def __init__(self):
        super(C3D, self).__init__()

        self.conv1 = nn.Conv3d(3, 64, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.pool1 = nn.MaxPool3d(kernel_size=(1, 2, 2), stride=(1, 2, 2))

        self.conv2 = nn.Conv3d(64, 128, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.pool2 = nn.MaxPool3d(kernel_size=(2, 2, 2), stride=(2, 2, 2))

        self.conv3a = nn.Conv3d(128, 256, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.conv3b = nn.Conv3d(256, 256, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.pool3 = nn.MaxPool3d(kernel_size=(2, 2, 2), stride=(2, 2, 2))

        self.conv4a = nn.Conv3d(256, 512, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.conv4b = nn.Conv3d(512, 512, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.pool4 = nn.MaxPool3d(kernel_size=(2, 2, 2), stride=(2, 2, 2))

        self.conv5a = nn.Conv3d(512, 512, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.conv5b = nn.Conv3d(512, 512, kernel_size=(3, 3, 3), padding=(1, 1, 1))
        self.pool5 = nn.MaxPool3d(kernel_size=(2, 2, 2), stride=(2, 2, 2), padding=(0, 1, 1))

        self.fc6 = nn.Linear(8192, 4096)
        self.fc7 = nn.Linear(4096, 4096)
        self.fc8 = nn.Linear(4096, 21)

        self.dropout = nn.Dropout(p=0.5)

        self.relu = nn.ReLU()
        self.softmax = nn.Softmax()

    def forward(self, x):

        h = self.relu(self.conv1(x))
        h = self.pool1(h)

        h = self.relu(self.conv2(h))
        h = self.pool2(h)

        h = self.relu(self.conv3a(h))
        h = self.relu(self.conv3b(h))
        h = self.pool3(h)

        h = self.relu(self.conv4a(h))
        h = self.relu(self.conv4b(h))
        h = self.pool4(h)

        h = self.relu(self.conv5a(h))
        h = self.relu(self.conv5b(h))
        h = self.pool5(h)

        h = h.view(-1, 8192)
        h = self.relu(self.fc6(h))
        h = self.dropout(h)
        h = self.relu(self.fc7(h))
        h = self.dropout(h)

        logits = self.fc8(h)

        return logits